***

# Curriculum Vitae

***

# Alan	Selewa
```selewa@uchicago.edu```

## Education

**Ph.D., Biophysical Sciences**                   
University of Chicago  
2016 - Present

**B.Sc., Physics**                                
University of Illinois at Urbana-Champaign  
2009 - 2014

## Honors & Awards

Undergraduate Research Symposium Award             
Shell Scholar Undergraduate Research Award         
Robert A. Stein Award                             

## Publications

[ 1 ] S. Banerjee, K. Lo, M.K. Daddysman, **A. Selewa** , T. Kuntz, A.R. Dinner, N.F.
Scherer, “Crossover in the dynamics of cell growth controls Caulobacter division times,”
**Nat. Microbiol. 2,** 17116 _(2017)._

[ 2 ] T. Huynh, M.K. Daddysman, Y. Bao, **A. Selewa** , A. Kuznetsov, L.H. Philipson, N.F.
Scherer, "Correlative imaging across microscopy platforms using the fast and accurate
relocation of microscopic experimental regions (FARMER) method," **Rev. Sci. Instrum.
88,** 15. (2017).

## Invited Talks

“Volumetric Image Reconstruction in Multi-focal Microscopy,” Argonne National Laboratory, June 6th, 2016.  

## Research Experience

**Research Specialist**                             
Department of Chemistry  
University of Chicago  
PI: Norbert Scherer 
2015 - 2016  

Algorithms for image analysis of microbes

**Undergraduate Research Assistant**                
Department of Physics  
University of Illinois at Urbana-Champaign  
PI: Liang Yang  
2013 - 2014  

Quantifying trace amounts of radioactive contamination in sodium-iodide scintillator
detectors through experiment and simulation.

## Teaching Experience

**Teaching Assistant**                             
ECE 340 - Semiconductor Physics
University of Illinois at Urbana-Champaign  
Fall 2014  

**Teaching Assistant**                                
ENG 10 0 – Introduction to Engineering  
University of Illinois at Urbana-Champaign   
2012 - 2013


